### ISSUE TITLE
Search give 404

### ISSUE THREAD

**Issue by Hinny** [CGJennings/se3docs#2]
When using the search bar on the top, many search results give faulty urls.

Example:
When typing "StrangeImage" into the search bar you get the following link as the number 1 result:
http://se3docs.cgjennings.ca/assets/javadoc/undefined/resources/StrangeImage.html
...which results to a 404.

The correct url is:
http://se3docs.cgjennings.ca/assets/javadoc/resources/StrangeImage.html

There is an extra /undefined/ in the faulty url.

**Comment by CGJennings** [comment]
This should be fixed&mdash;in fact it has been fixed for a while but I missed closing the issue!
